name: firma_prototype
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.0
  intl: ^0.15.7
  http: ^0.12.0
  flutter_secure_storage: ^3.1.2
  firebase_auth: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/firma_logo.png
   - assets/images/avatar1.png
   - assets/images/avatar2.png
   - assets/images/avatar3.png
   - assets/images/avatar4.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: CabinBold
      fonts:
        - asset: assets/fonts/CabinBold.ttf
